In [1]:
import pandas as pd
import plotly.express as px

In [2]:
df = pd.read_csv(r'ds_salaries.csv')

df.head(5)

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L

In [3]:
df_original = df.copy()

In [4]:
df_original.head()

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L

In [5]:
print("Shape : " , df_original.shape)
print("\n Tipos do dataset :\n", df_original.dtypes)

Shape :  (607, 12)

 Tipos do dataset :
 Unnamed: 0            int64
work_year             int64
experience_level        str
employment_type         str
job_title               str
salary                int64
salary_currency         str
salary_in_usd         int64
employee_residence      str
remote_ratio          int64
company_location        str
company_size            str
dtype: object

In [6]:
df_original.info()

<class 'pandas.DataFrame'>
RangeIndex: 607 entries, 0 to 606
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          607 non-null    int64
 1   work_year           607 non-null    int64
 2   experience_level    607 non-null    str
 3   employment_type     607 non-null    str
 4   job_title           607 non-null    str
 5   salary              607 non-null    int64
 6   salary_currency     607 non-null    str
 7   salary_in_usd       607 non-null    int64
 8   employee_residence  607 non-null    str
 9   remote_ratio        607 non-null    int64
 10  company_location    607 non-null    str
 11  company_size        607 non-null    str
dtypes: int64(5), str(7)
memory usage: 73.8 KB

In [7]:
print("Estatisticas gerais :\n" , df_original.describe())

Estatisticas gerais :
        Unnamed: 0    work_year        salary  salary_in_usd  remote_ratio
count  607.000000   607.000000  6.070000e+02     607.000000     607.00000
mean   303.000000  2021.405272  3.240001e+05  112297.869852      70.92257
std    175.370085     0.692133  1.544357e+06   70957.259411      40.70913
min      0.000000  2020.000000  4.000000e+03    2859.000000       0.00000
25%    151.500000  2021.000000  7.000000e+04   62726.000000      50.00000
50%    303.000000  2022.000000  1.150000e+05  101570.000000     100.00000
75%    454.500000  2022.000000  1.650000e+05  150000.000000     100.00000
max    606.000000  2022.000000  3.040000e+07  600000.000000     100.00000

In [8]:
df_original.select_dtypes(include=["object"]) # variaveis qualitativas

C:\Users\danir\AppData\Local\Temp\ipykernel_9588\2235897342.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df_original.select_dtypes(include=["object"]) # variaveis qualitativas

,experience_level,employment_type,job_title,salary_currency,employee_residence,company_location,company_size
0,MI,FT,Data Scientist,EUR,DE,DE,L
1,SE,FT,Machine Learning Scientist,USD,JP,JP,S
2,SE,FT,Big Data Engineer,GBP,GB,GB,M
3,MI,FT,Product Data Analyst,USD,HN,HN,S
4,SE,FT,Machine Learning Engineer,USD,US,US,L
...,...,...,...,...,...,...,...
602,SE,FT,Data Engineer,USD,US,US,M
603,SE,FT,Data Engineer,USD,US,US,M
604,SE,FT,Data Analyst,USD,US,US,M
605,SE,FT,Data Analyst,USD,US,US,M
606,MI,FT,AI Scientist,USD,IN,US,L

In [9]:
df.drop(columns=['Unnamed: 0'], inplace=True)
df.drop(columns=['salary_currency'], inplace=True)
df.drop(columns=['salary'], inplace=True)

In [10]:
df.isnull().sum()

work_year             0
experience_level      0
employment_type       0
job_title             0
salary_in_usd         0
employee_residence    0
remote_ratio          0
company_location      0
company_size          0
dtype: int64

In [11]:
df.rename(columns={
    'work_year': 'Ano de Referencia',
    'experience_level': 'Nivel de Experiencia',
    'salary_in_usd': 'Salario em Dolar(Anual)',
    'employment_type': 'Tipo de Contratacao',
    'job_title': 'Cargo',
    'employee_residence': 'Residencia Funcionario',
    'remote_ratio': 'Modalidade de Trabalho',
    'company_location': 'Residencia Empresa',
    'company_size': 'Tamanho da Empresa'
    }, inplace=True)

In [12]:
df.head()

,Ano de Referencia,Nivel de Experiencia,Tipo de Contratacao,Cargo,Salario em Dolar(Anual),Residencia Funcionario,Modalidade de Trabalho,Residencia Empresa,Tamanho da Empresa
0,2020,MI,FT,Data Scientist,79833,DE,0,DE,L
1,2020,SE,FT,Machine Learning Scientist,260000,JP,0,JP,S
2,2020,SE,FT,Big Data Engineer,109024,GB,50,GB,M
3,2020,MI,FT,Product Data Analyst,20000,HN,0,HN,S
4,2020,SE,FT,Machine Learning Engineer,150000,US,50,US,L

In [13]:
experiencia = {
    'EN': 'Junior',
    'MI': 'Pleno',
    'SE': 'Senior',
    'EX': 'Executivo'
}

df['Nivel de Experiencia'] = df['Nivel de Experiencia'].replace(experiencia)

In [14]:
contratacao = {
    'FT': 'Tempo Integral',
    'PT': 'Meio Periodo',
    'FL': 'FreeLancer',
    'CT': 'Contrato(PJ)'
}

df['Tipo de Contratacao'] = df['Tipo de Contratacao'].replace(contratacao)

In [15]:
modalidade = {
    0: 'Presencial',
    50: 'Hibrido',
    100: 'Online'
}

df['Modalidade de Trabalho'] = df['Modalidade de Trabalho'].replace(modalidade)

In [16]:
df['Modalidade de Trabalho'] = df['Modalidade de Trabalho'].astype(str)

In [17]:
df['Modalidade de Trabalho'].dtype

In [18]:
tamanho = {
    'L': 'Grande',
    'S': 'Pequena',
    'M': 'Media'
}

df['Tamanho da Empresa'] = df['Tamanho da Empresa'].replace(tamanho)

In [19]:
cargos = {
    'Data Scientist': 'Cientista de Dados',
    'Machine Learning Scientist': 'Cientista de Machine Learning',
    'Big Data Engineer': 'Engenheiro de Big Data',
    'Product Data Analyst': 'Analista de Dados de Produto',
    'Machine Learning Engineer': 'Engenheiro de Machine Learning',
    'Data Analyst': 'Analista de Dados',
    'Lead Data Scientist': 'Cientista de Dados Líder',
    'Business Data Analyst': 'Analista de Dados de Negócios',
    'Lead Data Engineer': 'Engenheiro de Dados Líder',
    'Lead Data Analyst': 'Analista de Dados Líder',
    'Data Engineer': 'Engenheiro de Dados',
    'Data Science Consultant': 'Consultor de Ciência de Dados',
    'BI Data Analyst': 'Analista de Dados de BI',
    'Director of Data Science': 'Diretor de Ciência de Dados',
    'Research Scientist': 'Cientista Pesquisador',
    'Machine Learning Manager': 'Gerente de Machine Learning',
    'Data Engineering Manager': 'Gerente de Engenharia de Dados',
    'Machine Learning Infrastructure Engineer': 'Engenheiro de Infraestrutura de Machine Learning',
    'ML Engineer': 'Engenheiro de ML',
    'AI Scientist': 'Cientista de IA',
    'Computer Vision Engineer': 'Engenheiro de Visão Computacional',
    'Principal Data Scientist': 'Cientista de Dados Principal',
    'Data Science Manager': 'Gerente de Ciência de Dados',
    'Head of Data': 'Head de Dados',
    '3D Computer Vision Researcher': 'Pesquisador de Visão Computacional 3D',
    'Data Analytics Engineer': 'Engenheiro de Analytics',
    'Applied Data Scientist': 'Cientista de Dados Aplicado',
    'Marketing Data Analyst': 'Analista de Dados de Marketing',
    'Cloud Data Engineer': 'Engenheiro de Dados em Nuvem',
    'Financial Data Analyst': 'Analista de Dados Financeiros',
    'Computer Vision Software Engineer': 'Engenheiro de Software de Visão Computacional',
    'Director of Data Engineering': 'Diretor de Engenharia de Dados',
    'Data Science Engineer': 'Engenheiro de Ciência de Dados',
    'Principal Data Engineer': 'Engenheiro de Dados Principal',
    'Machine Learning Developer': 'Desenvolvedor de Machine Learning',
    'Applied Machine Learning Scientist': 'Cientista de Machine Learning Aplicado',
    'Data Analytics Manager': 'Gerente de Analytics',
    'Head of Data Science': 'Head de Ciência de Dados',
    'Data Specialist': 'Especialista em Dados',
    'Data Architect': 'Arquiteto de Dados',
    'Finance Data Analyst': 'Analista de Dados Financeiros',
    'Principal Data Analyst': 'Analista de Dados Principal',
    'Big Data Architect': 'Arquiteto de Big Data',
    'Staff Data Scientist': 'Cientista de Dados Staff',
    'Analytics Engineer': 'Engenheiro de Analytics',
    'ETL Developer': 'Desenvolvedor ETL',
    'Head of Machine Learning': 'Head de Machine Learning',
    'NLP Engineer': 'Engenheiro de PLN', 
    'Lead Machine Learning Engineer': 'Engenheiro de Machine Learning Líder',
    'Data Analytics Lead': 'Líder de Analytics'
}

df['Cargo'] = df['Cargo'].replace(cargos)

In [20]:
df.head(15)

,Ano de Referencia,Nivel de Experiencia,Tipo de Contratacao,Cargo,Salario em Dolar(Anual),Residencia Funcionario,Modalidade de Trabalho,Residencia Empresa,Tamanho da Empresa
0,2020,Pleno,Tempo Integral,Cientista de Dados,79833,DE,Presencial,DE,Grande
1,2020,Senior,Tempo Integral,Cientista de Machine Learning,260000,JP,Presencial,JP,Pequena
2,2020,Senior,Tempo Integral,Engenheiro de Big Data,109024,GB,Hibrido,GB,Media
3,2020,Pleno,Tempo Integral,Analista de Dados de Produto,20000,HN,Presencial,HN,Pequena
4,2020,Senior,Tempo Integral,Engenheiro de Machine Learning,150000,US,Hibrido,US,Grande
5,2020,Junior,Tempo Integral,Analista de Dados,72000,US,Online,US,Grande
6,2020,Senior,Tempo Integral,Cientista de Dados Líder,190000,US,Online,US,Pequena
7,2020,Pleno,Tempo Integral,Cientista de Dados,35735,HU,Hibrido,HU,Grande
8,2020,Pleno,Tempo Integral,Analista de Dados de Negócios,135000,US,Online,US,Grande
9,2020,Senior,Tempo Integral,Engenheiro de Dados Líder,125000,NZ,Hibrido,NZ,Pequena
10,2020,Junior,Tempo Integral,Cientista de Dados,51321,FR,Presencial,FR,Pequena
11,2020,Pleno,Tempo Integral,Cientista de Dados,40481,IN,Presencial,IN,Grande
12,2020,Junior,Tempo Integral,Cientista de Dados,39916,FR,Presencial,FR,Media
13,2020,Pleno,Tempo Integral,Analista de Dados Líder,87000,US,Online,US,Grande
14,2020,Pleno,Tempo Integral,Analista de Dados,85000,US,Online,US,Grande

In [21]:
df_original.sort_values(by='salary_in_usd', ascending=False)

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
252,252,2021,EX,FT,Principal Data Engineer,600000,USD,600000,US,100,US,L
97,97,2021,MI,FT,Financial Data Analyst,450000,USD,450000,US,100,US,L
33,33,2020,MI,FT,Research Scientist,450000,USD,450000,US,0,US,M
157,157,2021,MI,FT,Applied Machine Learning Scientist,423000,USD,423000,US,50,US,L
225,225,2021,EX,CT,Principal Data Scientist,416000,USD,416000,US,100,US,S
...,...,...,...,...,...,...,...,...,...,...,...,...
179,179,2021,MI,FT,Data Scientist,420000,INR,5679,IN,100,US,S
77,77,2021,MI,PT,3D Computer Vision Researcher,400000,INR,5409,IN,50,IN,M
238,238,2021,EN,FT,Data Scientist,4000,USD,4000,VN,0,VN,M
185,185,2021,MI,FT,Data Engineer,4000,USD,4000,IR,100,IR,M
176,176,2021,MI,FT,Data Scientist,58000,MXN,2859,MX,0,MX,S

In [22]:
df_original['experience_level'].unique()

<ArrowStringArray>
['MI', 'SE', 'EN', 'EX']
Length: 4, dtype: str

In [23]:
df_filtrado = df_original[(df_original['experience_level'] == 'EN') & (df_original['salary_in_usd'])]

In [24]:
df_filtrado.sort_values(by='salary_in_usd', ascending=False)

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
123,123,2021,EN,FT,Applied Data Scientist,80000,GBP,110037,GB,0,GB,L
505,505,2022,EN,FT,Data Scientist,120000,AUD,86703,AU,50,AU,M
91,91,2021,EN,FT,Data Science Consultant,65000,EUR,76833,DE,100,DE,S
272,272,2021,EN,FT,Data Science Consultant,65000,EUR,76833,DE,0,DE,L
269,269,2021,EN,FT,Data Engineer,55000,EUR,65013,DE,50,DE,M
163,163,2021,EN,FT,Data Science Consultant,54000,EUR,63831,DE,50,DE,L
496,496,2022,EN,FT,Data Engineer,52800,EUR,58035,PK,100,DE,M
304,304,2022,EN,FT,Data Engineer,40000,GBP,52351,GB,100,GB,M
10,10,2020,EN,FT,Data Scientist,45000,EUR,51321,FR,0,FR,S
316,316,2022,EN,FT,Data Engineer,35000,GBP,45807,GB,100,GB,M
16,16,2020,EN,FT,Data Engineer,4450000,JPY,41689,JP,100,JP,S
246,246,2021,EN,FT,Data Scientist,31000,EUR,36643,FR,50,FR,L
489,489,2022,EN,CT,Applied Machine Learning Scientist,29000,EUR,31875,TN,100,CZ,M
94,94,2021,EN,FT,Data Scientist,2200000,INR,29751,IN,50,IN,L
216,216,2021,EN,PT,Computer Vision Engineer,180000,DKK,28609,DK,50,DK,S
253,253,2021,EN,FT,Data Scientist,2100000,INR,28399,IN,100,IN,M
214,214,2021,EN,FT,Machine Learning Engineer,21000,EUR,24823,DE,50,DE,M
449,449,2022,EN,FT,ML Engineer,20000,EUR,21983,PT,100,PT,L
62,62,2020,EN,PT,Data Scientist,19000,EUR,21669,IT,50,IT,S
239,239,2021,EN,FT,Data Engineer,1600000,INR,21637,IN,50,IN,M
244,244,2021,EN,FT,AI Scientist,1335000,INR,18053,IN,100,AS,S
18,18,2020,EN,FT,Data Science Consultant,423000,INR,5707,IN,50,IN,M

In [25]:
df_filtrado2 = df_original[(df_original['experience_level'] == 'EN') & (df_original['salary_in_usd']) & (df_original['job_title'] == 'Applied Data Scientist')]

In [26]:
df_filtrado2 #Lembrar de excluir o mano da linha 123, só existe ele nesse cargo, nao vale apena estudar

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
123,123,2021,EN,FT,Applied Data Scientist,80000,GBP,110037,GB,0,GB,L

In [27]:
df.drop(123, inplace=True) #excluindo linha 123

df.reset_index

df.iloc[123] #verificando novo 123

Ano de Referencia                       2021
Nivel de Experiencia                  Junior
Tipo de Contratacao             Meio Periodo
Cargo                      Analista de Dados
Salario em Dolar(Anual)                10354
Residencia Funcionario                    ES
Modalidade de Trabalho               Hibrido
Residencia Empresa                        ES
Tamanho da Empresa                     Media
Name: 124, dtype: object

In [28]:
fig_salario_cargo = px.box(df, y='Salario em Dolar(Anual)', title='Distribuição de Salários (Outliers visíveis)')
fig_salario_cargo.show()

### Análise de Outliers
Observamos no boxplot que existem salários acima de $400,000. Estes podem ser outliers ou cargos de alto nível (Executivos). Decidimos mantê-los pois são dados reais e importantes para a análise de mercado.

In [29]:
fig_salario_experiencia = px.histogram(df, x='Nivel de Experiencia', title='Quantidade de Registros por Nível de Experiência')
fig_salario_experiencia.show()

In [30]:
media_por_ano = df.groupby('Ano de Referencia')['Salario em Dolar(Anual)'].mean().reset_index()
fig_salario_ano = px.line(media_por_ano, x='Ano de Referencia', y='Salario em Dolar(Anual)', title='Evolução do Salário Médio Anual (USD)')
fig_salario_ano.show()

In [31]:
fig_modalidade = px.box(df, x='Modalidade de Trabalho', y='Salario em Dolar(Anual)', title='Salário por Modalidade de Trabalho')
fig_modalidade.show()

In [32]:
print("Estatísticas descritivas:\n", df[['Salario em Dolar(Anual)', 'Ano de Referencia']].describe().round(2))

Estatísticas descritivas:
        Salario em Dolar(Anual)  Ano de Referencia
count                   606.00             606.00
mean                 112301.60            2021.41
std                   71015.82               0.69
min                    2859.00            2020.00
25%                   62726.00            2021.00
50%                  101185.00            2022.00
75%                  150000.00            2022.00
max                  600000.00            2022.00